import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";

import { RegisterModal } from "./component/modal/RegisterModal";
import { LoginModal } from "./component/modal/LoginModal";
import { AddnewModal} from "./component/modal/AddnewModal";
import { SearchModal } from "./component/modal/SearchModal";
import { ClientOnly } from "./component/ClientOnly";
import { NavBar } from "./component/navbar/NavBar";
import { ToastPro } from "./providers/ToastPro";
import { getCurrentUser } from "./action/getCurrentUser";
import { ContactModal } from "./component/modal/ContactModal";



const font=Josefin_Sans({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Service App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const curUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={font.className} >
        <ClientOnly>
          <NavBar curUser = {curUser}/>
          <RegisterModal />
          <LoginModal />
          <SearchModal />
          <AddnewModal />
          <ContactModal />
          <ToastPro />
          {/* <div className="fixed top-0 left-0 w-screen h-[70vh]  z-0  bg-gradient-to-b from-orange-600/75 via-blue-600/75 to-blue-100/5"></div> */}
        </ClientOnly>
        {children}
 
      </body>
    </html>
  );
}
